# Setting
set-option -g mouse on
set-window-option -g utf8 on


# `bind' is alias of `bind-key'
# `bind -n' is no-prefix bind
# `bind -r' enable repeat bind
# run is alias of run-shell

# Bind
## Prefix
set-option -g prefix C-t
unbind-key C-b
bind C-t send-prefix

## Window
bind    n   new-window
bind    C-n new-window
bind -r ]   next-window
bind -r [   previous-window
bind -r C-] next-window
bind -r C-[ previous-window
bind -r Right next-window
bind -r Left  previous-window

## Pane
bind    |   split-window -h
bind    -   split-window -v
bind -r C-h select-pane -L
bind -r C-j select-pane -D
bind -r C-k select-pane -U
bind -r C-l select-pane -R
bind -r h   resize-pane -L 5
bind -r j   resize-pane -D 5
bind -r k   resize-pane -U 5
bind -r l   resize-pane -R 5

## mouse scroll
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

##
bind    r   source-file ~/.tmux.conf
bind    c   copy-mode
bind    C-c copy-mode


## Unbind
