#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

current_branch=`git branch --show-current`
protected_branches='main master develop test'
if [[ " ${protected_branches[@]} " =~ " $current_branch " ]]; then
  echo "${current_branch} への直コミ禁止"
  exit 1
fi
