#!/bin/bash
# WIP: pythonで書いたら良くね？
COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

current_branch=$(git branch --show-current)
# # 後方最長一致除去
# branch_type=${current_branch%%/*}
# 前方最短一致除去
ticket_name=${current_branch#*/}
if [ -z "$ticket_name" ]; then
  exit 0
fi

string_contain() {
  string=$1
  pattern=$2
  # 前方最長一致除去した結果、
  # -z 文字列長が 0 ならば真
  [ -z "${string##*$pattern*}" ]
}
is_mac() {
  string_contain $OSTYPE darwin
}

first_line=$(head -n1 $COMMIT_MSG_FILE)
if [ -z "$first_line" ]; then
  # 一行目が空行であれば（--amendでなければ）以下を実行
  # 最初の一行の先頭を書き換える
  if is_mac; then
    # macは-iがlinuxと違う
    sed -i "" "1s/^/${ticket_name} /" $COMMIT_MSG_FILE
  else
    # TODO: linux は未検証！！
    sed -i "1s/^/${ticket_name} /" $COMMIT_MSG_FILE
  fi
fi
